sudo: false
language: php


cache:
  directories:
    - $HOME/.cache/bower
    - $HOME/.composer/cache
    - $HOME/.npm
    - /tmp/phantomjs

env:
  global:
    - TEST_DAV=$(tests/travis/changed_app.sh dav)
    - TC=litmus-v2
    - SRV_HOST_NAME=owncloud
    - SRV_HOST_PORT=8889
    - REMOTE_FED_SRV_HOST_NAME=owncloud
    - REMOTE_FED_SRV_HOST_PORT=8989
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

addons:
  apt: &common_apt
    packages:
    - realpath
    - net-tools
    - libxml2-utils
  hosts: &common_hosts
    - owncloud

before_install:
  - make
  - sh -c "if [ '$TEST_DAV' = '1' ] || [ '$TC' = 'selenium' ]; then bash tests/travis/before_install.sh $DB; fi"

install:
  - sh -c "if [ '$TEST_DAV' = '1' ] || [ '$TC' = 'selenium' ]; then bash tests/travis/install.sh $DB; fi"
  - sh -c "if [ '$TEST_DAV' = '1' ]; then bash apps/dav/tests/travis/$TC/install.sh; fi"

before_script:
  - sh -c "if [ '$TC' = 'selenium' ]; then bash tests/travis/start_php_dev_server.sh; fi"

script:
  - sh -c "if [ '$TC' = 'syntax' ]; then make test-php-lint ; fi"
  - sh -c "if [ '$TEST_DAV' != '1' ]; then echo \"Not testing DAV\"; fi"
  - sh -c "if [ '$TEST_DAV' = '1' ]; then echo \"Testing DAV\"; fi"

  - sh -c "if [ '$TEST_DAV' = '1' ]; then bash apps/dav/tests/travis/$TC/script.sh; fi"
  - sh -c "if [ '$TC' = 'selenium' ]; then bash tests/travis/start_ui_tests.sh; fi"
  - bash tests/drone/test-phpunit.sh

matrix:
  include:
    - php: 7.0
      env: DB_TYPE=sqlite TEST_SUITE=phpunit PHP_VERSION=7.0
    - php: 7.1
      env: DB_TYPE=sqlite TEST_SUITE=phpunit PHP_VERSION=7.1
    - php: 7.2
      env: DB_TYPE=sqlite TEST_SUITE=phpunit PHP_VERSION=7.2
  fast_finish: true
